# Generated by Django 6.0.4 on 2026-04-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0003_alter_seller_options_remove_seller_commission_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='level',
            field=models.CharField(choices=[('starter', '🌱 Starter'), ('ambasador', '🥈 Ambasador'), ('vip', '🥇 VIP')], default='starter', max_length=20, verbose_name='Poziom'),
        ),
        migrations.AddField(
            model_name='seller',
            name='referral_count',
            field=models.IntegerField(default=0, verbose_name='Liczba poleceń'),
        ),
    ]
