# Generated by Django 6.0.4 on 2026-04-18 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('content', models.TextField(verbose_name='Treść')),
                ('excerpt', models.TextField(blank=True, max_length=300, verbose_name='Zajawka')),
                ('author_name', models.CharField(default='Marcel Krzeja', max_length=100, verbose_name='Autor')),
                ('author_title', models.CharField(default='Założyciel & ekspert od zapachów', max_length=100, verbose_name='Tytuł autora')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True, verbose_name='Opublikowany')),
            ],
            options={
                'verbose_name': 'Artykuł',
                'verbose_name_plural': 'Artykuły',
                'ordering': ['-created_at'],
            },
        ),
    ]
