# Generated by Django 6.0.4 on 2026-04-13 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0002_product_category_product_concentration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Imię')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nazwisko')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('address', models.CharField(max_length=200, verbose_name='Ulica i numer')),
                ('city', models.CharField(max_length=100, verbose_name='Miasto')),
                ('postal_code', models.CharField(max_length=10, verbose_name='Kod pocztowy')),
                ('status', models.CharField(choices=[('new', 'Nowe'), ('confirmed', 'Potwierdzone'), ('shipped', 'Wysłane'), ('delivered', 'Dostarczone'), ('cancelled', 'Anulowane')], default='new', max_length=20, verbose_name='Status')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Łączna kwota')),
                ('note', models.TextField(blank=True, verbose_name='Uwagi do zamówienia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data zamówienia')),
            ],
            options={
                'verbose_name': 'Zamówienie',
                'verbose_name_plural': 'Zamówienia',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
            ],
            options={
                'verbose_name': 'Pozycja zamówienia',
                'verbose_name_plural': 'Pozycje zamówienia',
            },
        ),
    ]
