# Generated by Django 6.0.4 on 2026-04-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_shipping_cost_order_shipping_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='Kraj'),
        ),
        migrations.AddField(
            model_name='order',
            name='language',
            field=models.CharField(default='pl', max_length=10, verbose_name='Język'),
        ),
    ]
