# Generated by Django 6.0.4 on 2026-04-28 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_country_order_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(default='PLN', max_length=10, verbose_name='Waluta zamówienia'),
        ),
        migrations.AddField(
            model_name='order',
            name='currency_symbol',
            field=models.CharField(default='zł', max_length=5, verbose_name='Symbol waluty'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_cost_currency',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Koszt wysyłki w walucie'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_amount_currency',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Łączna kwota w walucie'),
        ),
    ]
