# Generated by Django 6.0.4 on 2026-04-10 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('floral', 'Kwiatowe'), ('woody', 'Drzewne'), ('fresh', 'Świeże'), ('oriental', 'Orientalne'), ('citrus', 'Cytrusowe')], max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='concentration',
            field=models.CharField(choices=[('edt', 'EDT'), ('edp', 'EDP'), ('parfum', 'Parfum')], default='edp', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='intensity',
            field=models.CharField(blank=True, choices=[('light', 'Delikatna i świeża'), ('strong', 'Mocna i wieczorowa')], max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='occasion',
            field=models.CharField(blank=True, choices=[('daily', 'Na co dzień'), ('special', 'Specjalne wyjścia')], max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
