# Generated by Django 6.0.4 on 2026-04-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_category_product_concentration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='faq_json',
            field=models.TextField(blank=True, default='', verbose_name='FAQ (JSON)'),
        ),
    ]
