# Generated by Django 6.0.4 on 2026-04-28 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_faq_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='faq_json',
        ),
    ]
